# Generated by Django 4.2.2 on 2023-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_custompermission_rolegroup_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolegroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='permissions', to='users.custompermission'),
        ),
    ]
