# Generated by Django 4.2.2 on 2023-06-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rolegroup_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolegroup',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
