# Generated by Django 4.2.2 on 2023-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
