# Generated by Django 4.2.2 on 2023-06-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
    ]
