# Generated by Django 4.2.2 on 2023-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_alter_comment_reply_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CompanyTag',
            new_name='CompanyHiringTag',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.AddField(
            model_name='company',
            name='hiring_tags',
            field=models.ManyToManyField(related_name='hiring_tags', to='Company.companyhiringtag'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_tags',
            field=models.ManyToManyField(related_name='job_tags', to='Company.companyjobtag'),
        ),
    ]
